# GitHub CI build pipeline
name: Awesome Calculator CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      shell: bash
      run: |
        cd src
        python3 -m pip install --upgrade pip
        pip3 install coverage
        pip3 install twine
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Unit Tests and generate coverage report
      shell: bash
      run: |
        cd src
        python3 -m unittest -v
        coverage run -m unittest
        coverage report
        coverage html
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: src/htmlcov
    - name: Run package creation
      shell: bash
      run: |
        cd src
        python3 -m pip install --user --upgrade build
        python3 -m build
    - name: Deploy to TestPyPI
      run: |
        cd src
        twine upload --repository awesomecalculator dist/* --username __token__ --password pypi-AgENdGVzdC5weXBpLm9yZwIkYzVhMzlhMzYtMDdmNy00OGVhLTljOGItZDZlOTk0YTllZTA5AAIqWzMsIjMzOWMyNTY2LThjMWUtNGQyZC05OTA2LWVlOTk0N2Y4ODY3YiJdAAAGICjX6Prq_x6j8b3xhCB3rsUXuqPrUz38t1yQ4u5wMOKQ
